import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { clerkMiddleware } from '@clerk/nextjs/server';
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner"
import { ExitModal } from "@/components/modals/exit-modal";
import { HeartModal } from "@/components/modals/hearts-modal";
import { PracticeModal } from "@/components/modals/practice-modal";

const font = Nunito({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.variable} antialiased`}
      ><ClerkProvider>
          <Toaster />
          <ExitModal />
          <HeartModal />
          <PracticeModal />
          {children}
        </ClerkProvider></body>
    </html>
  );
}
